CREATE TABLE IF NOT EXISTS BOOKS (
 id BIGINT PRIMARY KEY NOT NULL,
 title VARCHAR(50) NOT NULL
);

CREATE SEQUENCE IF NOT EXISTS BOOK_SEQ_ID;

CREATE TABLE IF NOT EXISTS AUTHORS (
 id BIGINT PRIMARY KEY NOT NULL,
 author_name VARCHAR (250) NOT NULL UNIQUE
);

CREATE SEQUENCE IF NOT EXISTS AUTHOR_SEQ_ID;

CREATE TABLE IF NOT EXISTS GENRES (
  id BIGINT PRIMARY KEY NOT NULL,
  genre_name VARCHAR (50) NOT NULL
);

CREATE SEQUENCE IF NOT EXISTS GENRE_SEQ_ID;

CREATE TABLE IF NOT EXISTS BOOKS_AUTHORS (
  book_id BIGINT NOT NULL,
  author_id BIGINT NOT NULL,
  FOREIGN KEY (book_id) REFERENCES BOOKS(id),
  FOREIGN KEY (author_id) REFERENCES AUTHORS(id)
);

CREATE TABLE IF NOT EXISTS BOOKS_GENRES (
  book_id BIGINT NOT NULL,
  genre_id BIGINT NOT NULL,
  FOREIGN KEY (book_id) REFERENCES BOOKS(id),
  FOREIGN KEY (genre_id) REFERENCES GENRES(id)
);



